# Generated by Django 4.1.7 on 2023-03-22 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_userfollows_start_date_userfollows_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('subscriber', 'subscription')},
        ),
    ]
