# Generated by Django 4.1.7 on 2023-03-23 11:21

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_userfollows_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='subscription',
            field=models.CharField(max_length=128, null=True, verbose_name=authentication.models.User),
        ),
    ]
