# Generated by Django 4.1.7 on 2023-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=8192),
        ),
    ]
